### ISSUE TITLE
Difficulty with ST3/LatexTools

### ISSUE THREAD

**Issue by swang87** [andrewheiss/SublimeKnitr#27]
I have followed the instructions precisely for installation (including the patch to LaTeXTools), but can't seem to get the .Rnw files to compile. 

By default, it appears that the .Rnw files are being interpreted as straight-up LaTeX files. If I force a compilation via the R Sweave build system, only then is the .tex file is generated, but a .pdf is not generated. I have to then open up the .tex file and manually choose to compile via the LaTeX build system in order to complete the PDF compilation.

Minimal working example, which I saved as test.Rnw:

```
\documentclass{article}
\begin{document}

<<calc>>=
5 + 5
@

\end{document}
```

**Comment by zhuzelong** [comment]
The same issue. I patched the LaTeXTools as well.

Now I cannot build a pure TeX file (`.tex`) either. I selected `Build` or press `super + b` but nothing happened, nor a warning or error.

**Comment by swang87** [comment]
@zhuzelong Glad you are at least able to compile .tex files now. I wish there would be some clearer guidance on getting .Rnw files to work.

**Comment by swang87** [comment]
@dfeng You are a godsend. Thanks, this fixed my problem!

**Comment by andrewheiss** [comment]
I'll pull this in later tonight
